[default.flask]
SECRET_KEY = "secret-key"
TESTING = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://user:password@localhost/pkuphysu_db"

[default.jwt]
JWT_SECRET_KEY = "secret-key"
JWT_EXPIRATION_HOURS = 24

[default.wechat]
APP_ID = ""
APP_SECRET = ""
TOKEN = ""
MASTER_IDS = ["MASTER"]

[default.emails]
SMTP_SERVER = "smtphz.qiye.163.com"
SMTP_PORT = 994
SENDER_EMAIL = "your-account@domain.com"
SENDER_PASSWORD = "your-password"

[default.eveparty]
PRIZE_COUNT = 3
PRIZE_NAMES = ["一等奖", "二等奖", "三等奖"]
EVENT = "eveparty"

[default.logging]
version = 1

[default.logging.root]
level = "INFO"
handlers = ["wsgi"]

[default.logging.formatters.default]
format = "[%(asctime)s] %(levelname)s in %(name)s:%(funcName)s %(message)s"

[default.logging.handlers.wsgi]
class = "logging.StreamHandler"
level = "DEBUG"
stream = "ext://flask.logging.wsgi_errors_stream"
formatter = "default"